writeInfo: "1a "
pauseScript: "1b"
appendInfo: "1b "
pauseScript: "1c before"
appendInfo: "1c "
pauseScript: "1c after"
runScript: "deepPausePath/folder2/script2.praat"
pauseScript: "1d"
appendInfo: "1d "
pauseScript: "1e before"
appendInfo: "1e "
pauseScript: "1e after"
runScript: "deepPausePath/folder3/script3.praat"
pauseScript: "1f"
appendInfo: "1f "
pauseScript: "1g before"
appendInfo: "1g "
pauseScript: "1g after"
runScript: "deepPausePath/folder4/script4.praat"
pauseScript: "1h before"
appendInfo: "1h "
pauseScript: "1h after"
info$ = info$()
assert info$ = "1a 1b 1c 2a 2+ 2b 1d 1e 3a 3+ 3b 1f 1g 4a 4+ 4b 1h "
